print("Read Methods: ")
print('''
      1] Read()
      2] Readline()
      3] Readlines()
      ''')
f = open("Sample.txt", 'r')
print(f.tell())
print(f.read())
print(f.tell())
f.seek(0)
print(f.tell())
print("Read lines- returns list of new lines ",f.readlines())
print(f.tell())
f.seek(0)
print(f.tell())
print("Read line - returns single line till /n ",f.readline())

f=open("sample.txt") 
print(f.read(-5))
f.seek(0)
print(f.read(100))
f.seek(0)
print(f.read(5))
print(f.tell())
print(f.read(7))   
print(f.tell())
f.readline() 
print(f.tell())
